version: '3.8'
  
services:
    db:
        image: mysql        
        container_name: db_docker_symfony
        restart: always
        volumes:
                - db-data:/var/lib/mysql
                - ./db-init:/docker-entrypoint-initdb.d       
        environment:
                # MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'                
                MYSQL_ROOT_PASSWORD: $APP_MP
                MYSQL_DATABASE : $APP_MD
        ports:
            - "3306"
        expose:
            - "3306"
        
        networks:
            - devops      
        
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_docker_symfony
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - devops

    maildev:
        image: maildev/maildev
        container_name: maildev_docker_symfony
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        ports:
            - "8081:80"
        restart: always
        networks:
            - devops
            
    jenkins:
        image: jenkinsci/blueocean
        user: "root"
        volumes:
            - ../jenkins-data:/var/jenkins_home
            - /var/run/docker.sok:/var/run/docker.sock # Expose the docker deamon in the container. permettre au serveur jenkins de builder des images et d’utiliser des agents docker pour l’exécution des stages
            - ./:/home
        ports:
            - "8085:8080"
        networks:
            - devops    
                
    www:
        image: whatwedo/symfony5:v2.3
        container_name: www_docker_symfony        
        ports:
            - "8741:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./:/var/www
        restart: always
        networks:
            - devops

networks:
    devops:

volumes:
    db-data:
